server:
  port: 9099

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/kg_movie?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.springboot.project.module.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug